Miners/PalginHSR.ps1, Wrapper.ps1
This adds the Palgin miner back and attempts to fix the benchmark results.
Note that you need at least a 240 second benchmark interval to read the results, anything lower might fail.
Produced benchmark results are now correct, at least in my particular case (8 GPU rig).
=> Palgin fix attempt

NPlusMiner-v1.3.ps1
This is untested. Will try it out later
=> Address issue #313

prerun/default.bat
tested and work with win 7 + 1050ti.
=> restart display driver if gpu down

prerun/default.bat
=> thanks nemos!

Consumption/Consumption.json, Consumption/Readme.txt, NemosMinerv2.5.2.ps1
Added the option of taking into account the electricity cost in the profit.
It's optional using the respective parameter.
It will appear in the stats the cost of the electricity per algorithm.
=> Electricity Cost

Miners/DSTM.ps1
From version 0.6 changelog:
- ui: add colorized output
=> DSTM miner: add fancy --color parameter

Miners/ccminerRaven.ps1
Because it was the fastest enabled (not optional) x16r miner in the current master.
Tested on a single 1080 with 2x 10 minute benchmark time.
=> Bring back ccminerRaven

Miners/EthashClaymore.ps1
There were 2 space after EthDcrMiner64.exe
=> No space needs here

Miners/Bminer.ps1, Miners/ccminerDumax.ps1, Miners/ccminerTpruvotphi.ps1, OptionalMiners/ccminercool.ps1
CcminerDumax: v0.9.2
CcminerTpruvotphi: -a allium -i 22.125; you can also build v2.3 (latest, target date 6/23) from the latest commit from here: https://github.com/tpruvot/ccminer/commit/d9f242b8d1a1ef46e584f69666450fbc4431db15 and then add sonoa algorithm as well
Bminer: v9.0.0
Ccminercool: -a lyra2z -i 20.5; this can also be updated to v1.4 if you upload to your own repository since your link is to v1.1, links are here https://bitcointalk.org/index.php?topic=4412370.0
=> Update Miners:  CcminerDumax, CcminerTpruvotphi, Bminer, Ccminercool

Algorithms.txt, Miners/CuBalloon.ps1
=> Deft (balloon) #661

Include.ps1, NemosMiner.ps1
Wow you are fast at finding other people's changes!  I wasn't actually done when you merged the branch though.
This adds:
- Option to start paused, so earnings tracking starts automatically but mining does not
- Option to mine only when the system is idle - I mine on my gaming systems, so this means I can just leave nemosminer running in the background and it will automatically start mining when I'm not using the system.
=> Uialwaysactive

Include.ps1, NemosMiner.ps1
=> Flag for restarting cycle runspace

Miners/Ethminer.ps1
To make sure binary gets redownloaded
=> New binary path for ethminer

Include.ps1, NemosMiner.ps1
As promised in #802, here is it!
The server component needs to be installed on a webserver with php and mysql.  It's available here: https://github.com/grantemsley/NemosMiner-MonitorServer
The server also has full setup instructions and other information.
A demo of it is working at https://mining.emsley.ca
=> Monitoring

README.md
https://nemosminer.com
NemosMiner Monitoring Server
Keep tabs on all your mining rigs from one place!
=> nemosminer.com

Pools/zpool.ps1
=> Pool Failling #870

Config/PoolsConfig-x21sOnPhiPhi.json, Core.ps1, README.md
x21s on phiphi RITO (thanks MrPlusGH)
=> implement per Pool Algo selection

OptionalMiners/Gminer.ps1
I can lose hash if the pool switches to another coin within the same algo.
=> Change --pers to auto

OptionalMiners/CryptoDredge.ps1
It helps to identify what's going on. For example red is for errors.
=> I like color

OptionalMiners/zealotenemy.ps1
=> Fix AeriumX's algorithm in z-enemy, it's aergo
